services:
  - type: web
    name: aeterna-sol-iv
    runtime: static
    buildCommand: "pip install -r requirements.txt && python main.py"
    staticPublishPath: webapp
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
