services:
  - type: static
    name: aeterna-sol-iv
    env: static
    buildCommand: "pip install -r requirements.txt && python main.py"
    publishPath: webapp
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
